sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
# Matrix failure enabled for https://github.com/TheLarkInn/LazyParseWebpackPlugin/issues/6
matrix:
  fast_finish: true
  allow_failures:
  - node_js: "4"
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run lint
  - npm test
  - npm run build:prod
  - npm run server:prod:ci &
  - sleep 3
  - npm run e2e

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: www.spottersaver.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/SpotterSaver"
